"""Add voice_evaluations table

Revision ID: 094bcc3a5167
Revises: 3ebc18e4e56b
Create Date: 2025-09-28 10:01:41.047466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094bcc3a5167'
down_revision: Union[str, Sequence[str], None] = '3ebc18e4e56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('voice_profile_id', sa.UUID(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'brands', ['id'])
    op.create_unique_constraint(None, 'voice_profiles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_profiles', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')
    op.drop_table('voice_evaluations')
    # ### end Alembic commands ###
